version: "3.4"

services:
  nginx:
    build: .
    image: dynamedia/docker-nginx:v1.20.0
    environment:
      - USER_NAME=www-data
      - GROUP_NAME=www-data
      - USER_UID=1000
      - GROUP_GID=1000
    restart: always
    ports:
      - 80:80
   # volumes:
   #   - ./config/custom/nginx.conf:/etc/nginx/nginx.conf
   #   - ./geoip.mmdb/:/etc/nginx/geoip.mmdb
